### ISSUE TITLE
Implement a style guide

### ISSUE THREAD

**Issue by bmann** [fission-suite/landing-page#24]
As per discussion with @icidasset.

Please write comments to make this a more useful issue ;)

**Comment by forgondolin** [comment]
I think that would be great some svg's for using as font awesome.

**Comment by matheus23** [comment]
@forgondolin This issue came to be from a conversation in a PR. Here's a message from [that conversation](https://github.com/fission-suite/landing-page/pull/23#discussion_r469369552):

>  I try to alphabetize these classes so it's easier to look up a style and changing it.
> And then I put an empty comment to before the responsive styles.
> I realise that this may sound fairly obsessive, but there you go sweat_smile
>
> ```
> [ T.appearance_none
> , T.bg_gray_200
> , T.mt_8
> 
> --
> , T.md__text_lg
> ]
> ```
>
> Could also do the following, which I almost always do for the dark styles anyway:
> 
> ```
> -- Responsive
> -------------
> , T.md__text_lg
> ]
> ```

So, we're talking about code style in elm (esp. using elm-tailwind-css).

**Comment by bmann** [comment]
I'll call this a dupe of #36
