### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by bmann** [fission-suite/landing-page#27]
IPFS 0.6 gateway now [supports 404 pages](https://github.com/ipfs/go-ipfs/releases/tag/v0.6.0):

> You can now customize 404 Not Found error pages by including an ipfs-404.html file somewhere in the request path. When a requested file isn't found, go-ipfs will look for an ipfs-404.html in the same directory as the requested file, and in each ancestor directory. If found, this file will be returned (with a 404 status code) instead of the usual error message.

This needs to be static, I think we can use the Five creatures spaceship

Also: add this to the Guide

**Comment by matheus23** [comment]
Should we ask bruno for a design for this, or should I try my hands at designing that page quickly?

**Comment by bmann** [comment]
Hey @matheus23 I think just go ahead and use the shell of the page and I’ll check in the graphic.
