### ISSUE TITLE
Add GH Actions to build

### ISSUE THREAD

**Issue by bmann** [fission-suite/landing-page#37]
@walkah there is a `fissioncodes` key in 1P, can you set up github actions for this repo, please. `fissioncodes.fission.app` is the app name that can be "staging".

This is all working in the open, so LMK if moving the eleventy branch to main or whatever is helpful. We'll re-point the live DNS when we're ready.

**Comment by walkah** [comment]
All set! When eleventy gets merged to main, we'll need a one line tweak but all set for now.
