### ISSUE TITLE
Blog page not updating

### ISSUE THREAD

**Issue by walkah** [fission-suite/landing-page#68]
It looks like the blog landing page and the "from the blog" section on the homepage aren't pulling in newly published blog posts anymore:

https://fission.codes/blog/ should include the latest blog post: https://fission.codes/blog/verifying-ucans/

**Comment by avivash** [comment]
i found the culprit. it looks like the post is being pulled in from ghost, but then the posts are run through this sorter for that looks for a `featured` property. The new post has `featured: false`, but Web3 at CascadiaJS has `featured: true`. I don't have access to that post in ghost, but does someone want to set it to `featured: true`? Alternatively, I can just remove this code snippet if we don't want it anymore :person_shrugging: 
```
    // Bring featured post to the top of the list
    collection.sort((post, nextPost) => nextPost.featured - post.featured);
```
CC: @walkah @bmann

**Comment by walkah** [comment]
According to #9 - it's by design. My bad!
